### ISSUE TITLE
Fatal error: exception Sys_error("plan.sjson: Is a directory") with docker image

### ISSUE THREAD

**Issue by hiqua** [colis-anr/morbig#10]
Hi,
using the docker image and defining the shell function, I encounter a `Fatal error: exception Sys_error("script.sjson: Is a directory")` error. The file mentioned is created, but empty.

Is there a workaround?

I haven't tried compiling morbig myself yet, so I don't know if the error also happens in that case.

**Comment by Niols** [comment]
Hello,

I believe that it is because of the `-v $1.sjson:/home/opam/$B.sjson` that is meant to mount directories. That fact that the file is created is because of the `touch` command in the `morbig` shell function provided in the README.

By removing this option and/or the `touch` command, I got rid of the option. However, there is still nothing in the `.sjson` file.

**Comment by Niols** [comment]
Hello again,

The problem comes from the use of the `-v` argument for `docker run` in the `morbig` shell function provided in the README. This option is meant to mount *directories*. Hence:

- when trying to open `test.sh.json` for writing in the Docker image, morbig fail complaining that it is a directory;
- when trying to read `test.sh`, morbig should faill, because it is a directory (However, it does not because of #11).

As a workaround, I would use the following `morbig` shell function:

    morbig () {
        D=$(cd "$(dirname "$1")"; pwd)
        B=$(basename "$1")
        docker run \
            -v "$D":/mnt \
            morbig --as simple /mnt/"$B"
    }

where I am mounting the whole directory containing the file provided as first argument of the command as `/mnt` in the docker image. I can then run `morbig --as simple /mnt/<the file>` and everything that morbig creates in `/mnt` is also created on the filesystem outside of the docker image.

PS: I am using `$(cd "$(dirname "$1")"; pwd)` and not only `$(dirname "$1")` because, for some reason, docker complains when the directory to mount is only `.`
PPS: I could not build the docker image only with `docker build -t morbig`, I needed to specify the root directory. In my case, with `docker build -t morbig .`

**Comment by Niols** [comment]
I have fixed the directory problem and put the new `morbig` function in the README. Thanks for your report!
