### ISSUE TITLE
Positions are wrong

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#27]
Morbig miscalculates positions in the input file. For instance, on the input file contining only one line:

true

Morbig reports the word "true" starting at column 4 and ending and columns 5.

**Comment by Niols** [comment]
The bug seems to be located in the prelexer, I'll keep investigating

**Comment by Niols** [comment]
OK, found it. It is because of how the lexing of shell works: it defines the separators instead of the tokens to recognize.

Which means that we read the word "true" character by character, adding them to a list somewhere. Then we encounter the newline, and we flush the list. And we add the positions that we get from the lexing engine. And these positions are those of… the newline character.

In fact, there is also an other bug here (fixed, wait for the push) where the lexing engine doesn't properly count newlines in positions (it should recognize true between (1,4) and (2,0) and not (1,4) and (1,5)).

**Comment by Niols** [comment]
I believe this is now fixed.

**Comment by treinen** [comment]
Thanks, it seems to be OK, now.

I notice that line numbering starts at 1 and column numbering starts at 0. Is that what it is supposed to be?

**Comment by Niols** [comment]
This is how it is supposed to be. At least this is how Emacs, Vim, and the Lexing module work. But don't ask me why!
