### ISSUE TITLE
Design the API

### ISSUE THREAD

**Issue by yurug** [colis-anr/morbig#44]
Discussion open! @Niols, shall you start?

**Comment by Niols** [comment]
Alright. The question is: what do we want in the API and what don't we want there?

I personally like having everything directly in the API instead of having to look randomly at different modules. A good alternative would be to have a very well documented API with lots of pointers towards all the other modules that might be useful. 

I also like it when the API is directly accessible from the main module (like `Libmorbig.parse_file` instead of `Libmorbig.API.parse_file`). But I don't know how to do that with OCamlBuild (it is fairly easy with Dune). Also, I like when the name of the module is the same as the name of the package (so that you use the package `morbig` and have `Morbig.parse_file`; once again, it is easy with Dune but I don't know about OCamlBuild).

Anyway, here is what I would like to see in the API (as a draft to start this discussion; saying that we do not want some things in there is perfectly fine):

---

### Parsing

- `parse_file`
- `parse_string`. Actually, I don't know about that one. If we want to stay minimalist, `parse_channel` could be enough. Also, I guess that the first argument is for the positions in the AST. In order not to be too surprising for a user, could that argument be optional?
- `interactive_parse` (or `parse_one`, or `parse`, or idk; but we will wait for #42 before having that).

### Serializing

I would say that we need either all of them or none of them in the API file (I would probably put them all there):

- `save_as_json` and `load_as_json` with an argument (optional, once again? to have the output simple)
- `save_as_dot`
- `save_as_binary` and `load_as_binary`

### Errors

Should they be in the API or in the `Errors` module? Both seem fine to me.

### CSTHelpers

There should be a pointer towards these in the main page of the documentation. I agree to say that they should probably not be in the API as there are a lot of them. (But again, why not?) By the way, we should clearly add more documentation for these helpers.

---

I can't think of anything else right now, but I wanted to start this conversation. Any thoughts?

**Comment by treinen** [comment]
I think that the Exceptions should be on the same level as the functions that may raise them. That is,
if parse_file is directly in Libmorbig, then the expceptions should also be there and not in an Errors submodule.

**Comment by yurug** [comment]
They are many things in your comment!

First, about the role of the API: Yes, it must probably contain *all* the entry points needed for the typical use cases since the interfaces of the other modules should not be published at all. The problem is to find the correct set of exposed features that we can promise to provide in the future.

Second, about the name of the API module: Yes, I would prefer to write `open Morbig` instead of `open LibMorbig.API`. If you know how to do that with dune, why do we not move to this build system? Is `menhir` finally (correctly) integrated? Otherwise, we could rename `API` into `Morbig` and `Morbig` to `MorbigDriver`. The `Makefile` could rename `morbigDriver` into `morbig` to get the right executable in the end.

About the Parsing section: I agree we should have a `parse_channel` at some point but this seems currently impossible to me because of ocamllex internal buffer. I indeed keep `interactive_parse` for 1.0 because I anticipate some implementation problems.

About the Errors section: I agree with both of you.

About CSTHelpers: I would only publish location-related functions. The others seem a bit specific.

**Comment by treinen** [comment]
CSTHelpers: you mean for instance to export unWord', but not unWord ? That means that one needs
the invers of the current on_located function, right?

I am not sure whether this is planned but there are some quite specific functions that need precise knowledge of the POSIX shell syntax, like for quote removal on strings. These should also be exported
(possibly in CSTHelpers, or some other submodule).

**Comment by yurug** [comment]
Yes, you are right: the most important functions to publish are probably the ones that carry knowledge about the POSIX standard (as we understand it). They must also have a clear use case.

What would be the use case of `quoteRemoval`?

**Comment by treinen** [comment]
We have used quote removal at several places in shstats, at the moment by making a custom copy of
the module unQuote (which is not good). For instance we need it in the static expander when we
want to know whether a command word is a special bulltin (since in that case the effect of an
assignment prefix changes), and for that we have to unquote the command word, Or when we analyse test expressions since the words making up that test expression may be quoted.

**Comment by yurug** [comment]
That's convincing! You win!

**Comment by Niols** [comment]
What you describe about moving things in OCamlbuild result in writting `Morbig.Morbig', wouldn't it? We could also have `Morbig.API` which is in my opinion slightly better than `Libmorbig.API`.

About Dune's support for Menhir, it is still in progress (but almost there!). There is currently a discussion about a bug that the new `(menhir ...)` stanza causes for OCaml versions prior to 4.05. The question is whether the bug should be worked around in Menhir or if the stanza should just require OCaml ≥ 4.06. The discussion is in this PR: https://github.com/ocaml/dune/pull/863. In any case, this wont be possible for the 0.9 release. But maybe we can keep it in mind for 1.0.

About `parse_channel`, I was thinking of something that just reads the channel until `EOF` before answering. But I am not sure that it is that useful.

**Comment by yurug** [comment]
Do you have anything more to add in the API? If not I create PR to implement all your suggestions.

**Comment by Niols** [comment]
I don't think I do

**Comment by treinen** [comment]
I can't think of anything else ATM. A good test will be whether one can still compile shstats (and get rid of the custom copy of unQuote) with the revised API of morbig.
