### ISSUE TITLE
what is the minimal version of ocaml required for building morbig?

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#51]
README.md says >= 4.02.1, opam says >= 4.02.3. Which one is right?

**Comment by Niols** [comment]
I actually don't know.

The OPAM file you looked at was out of date. I wanted to wait for the new OPAM package to be accepted to push it. It is now accepted and requires OCaml ≥ 4.03. But this is mainly because OPAM's CI only tests for OCaml ≥ 4.03.

I don't know if there are features that we use that prevent OCaml < 4.03 from being used. Maybe we can say (we have to update the README anyway) that OCaml ≥ 4.03 is officially supported but that Morbig might work on previous versions?

Does that sound too restrictive to you? Should we try to support 4.02.3? I know that it is the OCaml version in Debian Stretch, but we will not have a Morbig package for it, will we? After that, it will be fine, Buster will have OCaml 4.05.

**Comment by Niols** [comment]
By the way, our CI also only tests for ≥ 4.03 as it relies on OPAM's:
https://travis-ci.org/colis-anr/morbig/builds/426569519

**Comment by Niols** [comment]
But if we decide to support earlier versions of OCaml, I will definitely find a way to test them in the CI.

**Comment by treinen** [comment]
On my desktop machine (debian stable) morbig compiles fine with ocaml 4.02.3. It would be nice to offically support that version of OCaml.

**Comment by Niols** [comment]
The CI now tests 4.02.3. And, indeed, it builds correctly. Note that we have one dependency that requires > 4.02.1, so 4.02.3 is indeed the least (safe) supported OCaml version.

**Comment by treinen** [comment]
OK, I have modified the README.me.
